echo "# STB_ChatBot" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/andrewtantbwa/STB_ChatBot.git
git push -u origin main
